name: Main build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send to pipeline
        run: |
          echo $GITHUB_EVENT_NAME
