name: Pretend release

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ["Main build"]
    types: [completed]
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show stuff
        run: |
          echo $GITHUB_EVENT_NAME
